### ISSUE TITLE
No chat history exists, users should be able to connect to a room and be able to scroll infinitely through the history of that room

### ISSUE THREAD

**Issue by Matt-Allen44** [Matt-Allen44/Quik#36]
At the moment we're less feature complete than IRC :disappointed: 
This is one of the key features that will make a difference, a DB is likely required to log the messages.

**Comment by zelon88** [comment]
What if each chat were saved in a unique session ID. We could create a txt file and use file_put_contents to store chats by directory as a txt file and then use file_get_contents to search through them again later. Just a thought.

**Comment by Matt-Allen44** [comment]
The major issue I have with that is scalability, using something such as Redis or SQL will allow more scalability on a proven platform - I suspect there's a reason most website don't write there own database and storage software.

**Comment by zelon88** [comment]
Gotcha, and I agree a database would be the easiest to implement. My reasoning for suggesting file_put_contents with PHP to create static txt files is that 1) They are more easily searchable outside of your stack, 2) They are more reliable to backup / make copies of outside your stack, 3) They can be structured so that only Temp files are made available to the user upon request and deleted when not needed, but permanent copies are stored in a non-hosted, write-controlled location which makes your app; 4) More secure, easier to deploy, and impervious to sql injection with; 5) no extra overhead and; 6) no added dependencies (like a database). I don't find any fault with you logic, though, I just figured it would be a note-worthy suggestion (since I'd rather not need a database for the project). I trust that whatever you decide will be remarkable! Thanks for your time and keep up the good work! :)

**Comment by Matt-Allen44** [comment]
Redis logging has been implemented, loading chat history is not developed on the client side. :+1:
